/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css' 
import homeimage from '../public/home.jpg';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>   
          <span>&lt;Hunting Coder/&gt;</span>
        </h1>  
        <div className={styles.imagewrap}>
        <Image className={styles.homeimage} src={homeimage} alt = "coder image" height={345.6} width={518.4}></Image>
        </div>
        <p className={styles.description}>
          A blog for hunting Coders by A hunting Coder
        </p>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
